version: '3.1'
services:
  nginx:
    ports:
      - 3000:80
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./dist:/home/app/src
      - /home/app/node_modules
    environment:
      NODE_ENV: development
      MONGO_USER: admin
      MONGO_PASSWORD: password
    command: yarn dev
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
 