version: '3.1'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    image: 319692863428.dkr.ecr.us-west-2.amazonaws.com/node-app:latest
    environment:
      PORT: 3000
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis:7-alpine
volumes:
  mongo-db:
    driver: local
    